### ISSUE TITLE
[Bug] Firebase Messaging & Unity 6 - Not receiving notifications on Android

### ISSUE THREAD

**Issue by CDAfonso** [firebase/firebase-unity-sdk#1014]
### Description

Hi!

I have this new project using Unity Preview version 6000.0.0f1, using Firebase Messaging 
Everything is properly configured on the Firebase Console, the android logcat logs "Firebase Inittialized", but the it dosen't return a FCM token in the logs. Also, the notifications sent doesn't arrive.

Unity 6 is still new and i understand that it can take time to get a fully compatible version of firebase message working, but is there a way to make it work?

Thank so much.

### Firebase Unity SDK Version

11.9.0

### Unity editor version

6000.0.0f1

### Installation Method

.unitypackage

### Problematic Firebase Component(s)

Messaging

### Targeted Platform(s)

Android

### Unity editor platform

Windows

### Scripting Runtime

IL2CPP

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity

### Relevant Log Output

```shell
2024/05/07 09:24:31.797 7101 7101 Info FirebaseApp Device unlocked: initializing all Firebase APIs for app [DEFAULT]
2024/05/07 09:24:31.807 7101 7101 Info FirebaseInitProvider FirebaseApp initialization successful
2024/05/07 09:24:31.952 7101 7101 Info ForceDarkHelperStubImpl setViewRootImplForceDark: false for com.google.firebase.MessagingUnityPlayerActivity@5037e1e, reason: AppDarkModeEnable
2024/05/07 09:24:31.954 7101 8107 Info FA   adb shell setprop debug.firebase.analytics.app xxxxxxxxxxx
2024/05/07 09:24:32.025 7101 7101 Debug SurfaceView UPDATE Surface(name=SurfaceView[xxxxxxxxxxxxx/com.google.firebase.MessagingUnityPlayerActivity])/@0x1f8f06, mIsProjectionMode = false
2024/05/07 09:24:32.676 7101 7101 Warn Activity PerfMonitor: Slow Operation: Activity xxxxxxxxxxxxxxx/com.google.firebase.MessagingUnityPlayerActivity onPause took 183ms
2024/05/07 09:24:33.075 7101 8184 Info firebase Firebase Cloud Messaging API Initialized
2024/05/07 09:24:33.092 7101 8105 Info firebase Firebase Cloud Messaging API Initialized
2024/05/07 09:24:33.100 7101 8105 Info Unity Firebase Cloud Messaging API Initialized
2024/05/07 09:24:33.100 7101 8105 Info Unity Firebase.AppUtilPINVOKE:PollCallbacks()
2024/05/07 09:24:33.100 7101 8105 Info Unity Firebase.AppUtil:PollCallbacks()
2024/05/07 09:24:33.100 7101 8105 Info Unity Firebase.Platform.FirebaseHandler:Update()
2024/05/07 09:26:44.758 7101 7101 Warn Activity PerfMonitor: Slow Operation: Activity xxxxxxxxxxxx/com.google.firebase.MessagingUnityPlayerActivity onPause took 69ms
```

### If using CocoaPods for Apple platforms, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

👀 Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by argzdev** [comment]
Hi there, @CDAfonso. Thanks for reaching out. I tried testing our Firebase Messaging [quickstart](https://github.com/firebase/quickstart-unity) in Unity with version `6000.0.0f1`, and version `11.9.0` of Firebase Messaging, so far it seems to work. I was able to receive a token, and receive the message on foreground, and notification on background when testing on an Android 12 emulator. I did notice that the Android 13 does not receive a notification but that's due to the post [notification permission](https://developer.android.com/develop/ui/views/notifications/notification-permission) needed for Android 13 devices or higher.

You could also try and use our quickstart and see if there's any configuration difference that could be causing this issue. Let me know if this helps. Thanks!

**Comment by CDAfonso** [comment]
Thank you @argzdev!

After more testing, i can affirm that i am getting notifications on android, but ONLY WHEN APP IS BACKGROUND. 
If the app is in foreground, i can see message received on the android logcat, but it doesn't show on tray (Tried with 2 devices).

This is my manifest:
`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools" package="com.emequatro.mediatypo" android:versionCode="1" android:versionName="1.0">
<uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>
  <application android:label="@string/app_name" android:icon="@drawable/app_icon">
    
    <activity android:name="com.google.firebase.MessagingUnityPlayerActivity" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
      <meta-data android:name="unityplayer.UnityActivity" android:value="true" />
    </activity>
    <service android:name="com.google.firebase.messaging.MessageForwardingService" android:permission="android.permission.BIND_JOB_SERVICE" android:exported="false"></service>
    <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/notification_icon" />
  </application>
</manifest>`

**Comment by argzdev** [comment]
That's good to hear, @CDAfonso. Your `AndroidManifest.xml` looks alright. However, I see that there might be a misunderstanding of how our Firebase Messaging notifications work. So for context, in our [documentations](https://firebase.google.com/docs/cloud-messaging/concept-options#notification-messages-with-optional-data-payload):

> 1. When in the background, apps receive the notification payload in the notification tray, and only handle the data payload when the user taps on the notification.
> 2. When in the foreground, your app receives a message object with both payloads available.

In this case, since your app is on foreground, the app will receive the message in the app, but will not display anything in your notification tray. This is intended, and we do this to give our developers the freedom what to do with the provided information. If you'd like to display this in your notification, you would need to craft your own logic to display this.

Let me know if this answers your question, Thanks!

**Comment by CDAfonso** [comment]
Thank you, @argzdev  for your precious help. 
In my past projects, it worked without any aditional code, showing notifications even if the app is in foreground.
I've read that this changed in the latest sdk's... so how do we deal with this now in Unity?

Thank you so much.

**Comment by argzdev** [comment]
Hey @CDAfonso, since our [documentations](https://firebase.google.com/docs/cloud-messaging/unity/client#note_about_message_delivery_on_android) describes this behavior. You will need to add a logic to display your notification in the `OnMessageReceived` of Firebase Messaging.

First you need to register your `MessageReceived` callback when you initialize Firebase Messaging. You can refer to it [here](https://firebase.google.com/docs/cloud-messaging/unity/client#initialize).
```
public void Start() {
  ...
  Firebase.Messaging.FirebaseMessaging.MessageReceived += OnMessageReceived;
}
```

Once that is done, you can then add your logic for showing notifications in the `OnMessageReceived`
```
public void OnMessageReceived(object sender, Firebase.Messaging.MessageReceivedEventArgs e) {
  // Show notification here
  UnityEngine.Debug.Log("From: " + e.Message.From);
  UnityEngine.Debug.Log("Message ID: " + e.Message.MessageId);
}
```

**Comment by CDAfonso** [comment]
Thanks @argzdev , but how to get the message title and content? Can't find it anywhere.

**Comment by argzdev** [comment]
Awesome! Great to hear that it's working.
