### ISSUE TITLE
[Question] i don't know why please check URL

### ISSUE THREAD

**Issue by Jeremy221344** [firebase/firebase-unity-sdk#1020]
### What is your question?

https://github.com/googlesamples/google-signin-unity/issues/254

### Firebase Unity SDK Version

11.9.0

### Unity editor version

2022.3.27f1

### Installation Method

.unitypackage

### Problematic Firebase Component(s)

Analytics

### Other Firebase Component(s) in use

Analytics

### Additional SDKs you are using

Facebook, GoogleAdmob, LineSDK, GoogleSingin

### Targeted Platform(s)

Apple Platforms

### Unity editor platform

Mac

### Scripting Runtime

IL2CPP

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity

**Comment by argzdev** [comment]
Thanks for reaching out, @Jeremy221344. I've tried opening our Firebase Auth [quickstart in Unity](https://github.com/firebase/quickstart-unity) and then added `google-signin-plugin-1.0.4.unitypackage`, and so far the app was able to build correctly. I did encounter an issue where the package was conflicting, however I was able to resolve this by removing the Parse folder. If you also experience the same behavior, you can follow this [SO thread](https://stackoverflow.com/a/66303000/14129564). 

I noticed you mentioned Firebase Unity SDK version `11.9.0`. In order to use the `google-signin` you likely need to import Firebase Authentication as well. You may download the `unitypackage` for Firebase Auth [here](https://developers.google.com/unity/archive#firebase_authentication). Make sure to download and use the version you're currently using e.g. `11.9.0`
