### ISSUE TITLE
[Question] How to set Firebase logging level? (Android)

### ISSUE THREAD

**Issue by mohumohu-corp** [firebase/firebase-unity-sdk#1054]
### What is your question?

I am using FirebaseFunctions, but I get the following warning even when running the release build. 

I don’t plan to use the AppCheck feature for a while, so I would like to know how to eliminate such warnings from the release build.

```
FirebaseContextProvider Error getting App Check token. Error: com.google.firebase.FirebaseException: No AppCheckProvider installed.
```

![FirebaseContextProvider](https://github.com/firebase/firebase-unity-sdk/assets/85362386/7cd8c4e9-9d48-4188-8bce-1f4bdf52dda9)

### Firebase Unity SDK Version

12.1.0

### Unity editor version

2022.3.34f1

### Installation Method

Unity Package Manager

### Problematic Firebase Component(s)

All

### Other Firebase Component(s) in use

All

### Targeted Platform(s)

Android

### Unity editor platform

Windows

### Scripting Runtime

IL2CPP

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity

**Comment by argzdev** [comment]
Hi @mohumohu-corp, thanks for reaching out. Since Firebase Unity acts as a wrapper, the underlying Firebase Android SDK is the one showing this log warning. Right now, there isn't a way to change the logging level for Firebase AppCheck. This is currently a [requested feature](https://github.com/firebase/firebase-android-sdk/issues/3946) in the Firebase Android SDK. You may continue monitoring updates from that thread.

You may also help us prioritize adding this in the roadmap by leaving a thumbs up on the author's post of the referenced link.  I'll go ahead and close this thread to avoid duplicates. Thanks!
