### ISSUE TITLE
[Bug] [Crashlytics][Messaging] DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION causes "incorrectly registered broadcast receiver: error

### ISSUE THREAD

**Issue by AsafWhalo** [firebase/firebase-unity-sdk#1088]
### Description

Good day,

Upon uploading our game to the google play store we received this error in the dashboard
![image](https://github.com/user-attachments/assets/ec256a50-0975-49ba-936f-e144d1789312)

I eventually found that the issue is connected to these 2 additions to the AndroidManifest.xml :

`<permission android:name="com.DefaultCompany.TestingSite.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION" android:protectionLevel="signature"/>
    <uses-permission android:name="com.DefaultCompany.TestingSite.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION"/>`

which from what I understand is a cause of a unhandled broadcast receiver.

I have made a side project where I would build a APK after each 3rd party SDK we have in our main project, and would then unpack the APK and check the AndroidManifest.xml each time.

I found that when I added Firebase Crashlytics and Firebase Messaging unitypackage to the project, it would generate those permissions in the last AndroidManifest.xml

### Reproducing the issue

1. Create new project in Unity
2. Set project as IL2CPP, and:
![image](https://github.com/user-attachments/assets/1bedd8fe-960f-4723-b140-009a342f7320)

4. Add Crashlytics or Messaging unitypackage to the project
5. Just in case - run External dependency resolver
6. Build Project as Android, wait for APK
7. using apktool `https://formulae.brew.sh/formula/apktool` you can unpack APK
8. See last AndroidManifest.xml and search for `DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION`

### Firebase Unity SDK Version

12.0.1

### Unity editor version

2022.3.27f1

### Installation Method

.unitypackage

### Problematic Firebase Component(s)

Crashlytics, Messaging

### Other Firebase Component(s) in use

Analytics, Crashlytics, Messaging

### Additional SDKs you are using

Facebook, IronSource

### Targeted Platform(s)

Android

### Unity editor platform

Mac

### Scripting Runtime

IL2CPP

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity

**Comment by argzdev** [comment]
Hey @AsafWhalo, thanks for reaching out. After doing a bit of digging, looks like `DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION` isn't exactly the culprit of the issue. According to an explanation from the [F-Droid project](https://stackoverflow.com/a/78816850):
> Before API 33, registerReceiver() took the name of a signature-level permission to gate whether intents could be sent to dynamically registered broadcast intent receivers. If no permission was specified, it was exported to the world.

> In API 33, registerReceiver()'s flag argument gained explicit RECEIVER_EXPORTED and RECEIVER_NOT_EXPORTED controls. The use of RECEIVER_NOT_EXPORTED with no specified signature-level permissions means that the application intends to only send intents to itself, and reject them from elsewhere.

> In order to emulate API 33's RECEIVER_NOT_EXPORTED flag on older APIs, androidx's ContextCompat makes use of the fact that a signature-level permission that no other app uses amounts to the same thing as being not exported. So, AAPT merges into the manifest:
> ```
> <permission android:name="${applicationId}.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION"
>     android:protectionLevel="signature" />
> <uses-permission android:name="${applicationId}.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION"/>
> ```

> And then, on the older APIs, passes "${applicationId}.DYNAMIC_RECEIVER_ NOT_EXPORTED_PERMISSION" to registerReceiver()'s permission argument when RECEIVER_NOT_EXPORTED is specified.

Meaning, adding libraries such as `androidx.work:2.9.0`, or `androidx.core:core:1.9.0` will automatically include this permission. And since the Firebase SDKs normally use these or higher versions of those libraries, it will most definitely include the `DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION` permissions. I tried creating an empty native android app, and it seems to include this permission in the merged manifest.

That said, I'm wondering if there's any receivers that might've been incorrectly setup (e.g. having no export flag in the AndroidManifest.xml). Could you share me your merged manifest file, so I can check if there's anything unusual? Thanks!

**Comment by argzdev** [comment]
Thanks for the additional information, @AsafWhalo. From my testing, I tried using our Firebase quickstart Unity for FCM, and exporting the project so I can open it in Android Studio. So far the AndroidManifest.xml file only have one component with exported set to true. `com.google.firebase.MessagingUnityPlayerActivity`

Here's the entire AndroidManifest.xml
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools" android:versionCode="1" android:versionName="1.0">
  <uses-feature android:glEsVersion="0x00020000" />
  <uses-feature android:name="android.hardware.touchscreen" android:required="false" />
  <application android:label="@string/app_name" android:icon="@mipmap/app_icon" android:extractNativeLibs="true" android:isGame="true">
    <service android:name="com.google.firebase.messaging.MessageForwardingService" android:permission="android.permission.BIND_JOB_SERVICE" android:exported="false" />
    <meta-data android:name="unity.splash-mode" android:value="0" />
    <meta-data android:name="unity.splash-enable" android:value="True" />
    <meta-data android:name="unity.launch-fullscreen" android:value="True" />
    <meta-data android:name="unity.render-outside-safearea" android:value="True" />
    <meta-data android:name="notch.config" android:value="portrait|landscape" />
    <meta-data android:name="unity.auto-report-fully-drawn" android:value="true" />
    <activity android:name="com.google.firebase.MessagingUnityPlayerActivity" android:configChanges="mcc|mnc|locale|touchscreen|keyboard|keyboardHidden|navigation|orientation|screenLayout|uiMode|screenSize|smallestScreenSize|fontScale|layoutDirection|density" android:screenOrientation="fullUser" android:launchMode="singleTask" android:resizeableActivity="false" android:hardwareAccelerated="false" android:exported="true">
      <intent-filter>
        <category android:name="android.intent.category.LAUNCHER" />
        <category android:name="android.intent.category.LEANBACK_LAUNCHER" />
        <action android:name="android.intent.action.MAIN" />
      </intent-filter>
      <meta-data android:name="unityplayer.UnityActivity" android:value="true" />
      <meta-data android:name="notch_support" android:value="true" />
    </activity>
  </application>
</manifest>
```

Now with your attached `AndroidManifest.xml` I see 4 components where the exported is set to true
```
<activity android:configChanges="density|fontScale|keyboard|keyboardHidden|layoutDirection|locale|mcc|mnc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|touchscreen|uiMode" android:exported="true" android:hardwareAccelerated="false" android:launchMode="singleTask" android:name="com.unity3d.player.UnityPlayerActivity" android:resizeableActivity="false" android:screenOrientation="fullUser" android:theme="@style/UnityThemeSelector">
...
<activity android:exported="true" android:name="com.facebook.CustomTabActivity">
...
<receiver android:exported="true" android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver" android:permission="com.google.android.c2dm.permission.SEND">
...
<service android:exported="true" android:name="com.google.android.gms.messaging.cpp.MessageForwardingService" android:permission="android.permission.BIND_JOB_SERVICE"/>

```
Here are some of my observations:
1. The first component set to true is expected since this is similar to what I have in my `AndroidManifest.xml`. 
2. For the 4th component, `MessageForwardingService` did you manually change the export value to true? I believe this value should be set to false. According to the [docs](https://firebase.google.com/docs/cloud-messaging/unity/client#initialize), If you were using a custom entry point, you'd still need to set the export value to false.
3. For the 3rd component, did you manually add the `FirebaseInstanceIdReceiver`? I believe you don't necessarily need this to be able to receive FCM notifications.
