### ISSUE TITLE
[Bug] Callable functions request does not include Auth context in editor

### ISSUE THREAD

**Issue by PizzaPie144** [firebase/firebase-unity-sdk#1110]
### Description

Calling a callable function from Editor either targeting deployed function or functions emulator does not include Verifications-> Auth (missing) context. 

Works fine on Android build. 

Using anonymous authentication.

### Reproducing the issue

In Unity Editor, authenticate with anonymous auth. 
Once authentication is completed invoke a callable function, tried calls on various timings to make sure that it is not an issue relative to authentication completion. 
Request object received by function doesn't contain auth context.

Functions used is AddMessage example in [callable functions doc](https://firebase.google.com/docs/functions/callable?gen=2nd). 

Using either deployed function or functions emulator result is the same.

### Firebase Unity SDK Version

12.1.0

### Unity editor version

2022.3.30f1

### Installation Method

Unity Package Manager

### Problematic Firebase Component(s)

Authentication, Functions

### Other Firebase Component(s) in use

Database, Firestore, Storage

### Targeted Platform(s)

Android

### Unity editor platform

Windows

### Scripting Runtime

IL2CPP

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity

### Relevant Log Output

```shell
{
  "insertId": "xxx",
  "jsonPayload": {
    "message": "Callable request verification passed",
    "verifications": {
      "app": "MISSING",
      "auth": "MISSING"
    }
  },
  "resource": {
    "type": "cloud_run_revision",
    "labels": {
      "revision_name": "addmessage-xxx",
      "service_name": "addmessage",
      "location": "us-central1",
      "project_id": "xxx",
      "configuration_name": "addmessage"
    }
  },
  "timestamp": "2024-09-17T17:29:09.258142Z",
  "severity": "DEBUG",
  "labels": {
    "goog-managed-by": "cloudfunctions",
    "firebase-log-type": "callable-request-verification",
    "execution_id": "xxx",
    "instanceId": "xxx"
  },
  "logName": "xxx",
  "trace": "xxx",
  "receiveTimestamp": "2024-09-17T17:29:09.264748765Z",
  "spanId": "xxx"
}
```

### If using CocoaPods for Apple platforms, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

👀 Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by argzdev** [comment]
Thanks for reaching out, @PizzaPie144. I tried using our [Unity quickstarts for Firebase Functions](https://github.com/firebase/quickstart-unity), and tested out the functions of 1st and 2nd gen. It seems to be working correctly, and the auth context doesn't appear to be empty.

Here's my NodeJS functions.

1st gen:
```javascript
exports.addNumbersV1 = functions.https.onCall((data, context) => {
    ...
    const uid = context.auth.uid;
    functions.logger.info("auth: " + uid);
    ...
}
```
2nd gen:
```javascript

exports.addNumbersV2 = onCall((request) => {
    ...
    const uid = request.auth.uid;
    logger.info("uid: " + uid);
    ...
}
```

That said, I did notice that you're using an older version of the Unity Editor and Firebase SDK. Could you try updating to the latest version `2022.3.47f1` and `12.2.1`. We normally recommend this to avoid issues that might have been fixed in the most recent versions. Let me know if it works!

If it doesn't, could you share a [MCVE](https://meta.stackoverflow.com/questions/366988/what-does-mcve-mean) so we can investigate this further? Thanks!
