### ISSUE TITLE
[Bug] iOS: DynamicLinkReceived event doesn't invoke when app opens with dynamic links right after installation

### ISSUE THREAD

**Issue by Hedorda** [firebase/firebase-unity-sdk#346]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.3.39
  * Firebase Unity SDK version: 9.0.0
  * Source you installed the SDK: .unitypachage
  * Problematic Firebase Component: Dynamic Links
  * Other Firebase Components in use: Analytics
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity)

### [REQUIRED] Please describe the issue here:

Dynamic Links(we are using Custom Domain without Custom Scheme) opens app with invoking event `DynamicLinks.DynamicLinkReceived` if app has been installed and opens AppStore page if app hasn't been installed. However, after installation with Dynamic Link and opening app, `DynamicLinks.DynamicLinkReceived` doesn't invoking, user should tap the link second time to get this in the app. 

On Android and older versions Firebase SDK(e.g. 8.0.0) it works correctly: user can open app with DynamicLink right after installation.

#### Steps to reproduce:

1. Build XCode, check GoogleService-Info.plist file, `FirebaseDynamicLinksCustomDomains` in the Info.plist file, associated domains. Deploy into AppStore
2. Create dynamic link with custom domain without Custom Scheme in firebase console/api. Link should open appstore if application not installed
3. Unistall the app from device
4. Click link, it opens appstore page.
5. Install the app
6. Open the app

Expected behavior:

  * `DynamicLinks.DynamicLinkReceived` invoked then app opens

Real behavior:
 
* `DynamicLinks.DynamicLinkReceived` didn't invoke then app opens

When Im opening installed app from this link all works as expected.

No errors or unexpected messages in unity logs, xcode build and running logs. 

#### Relevant Code:

```
    void Start()
    {
        DynamicLinks.DynamicLinkReceived += OnDynamicLink;
    }
    private void OnDynamicLink(object sender, EventArgs args) 
    {
            var dynamicLinkEventArgs = args as ReceivedDynamicLinkEventArgs;
            ShowMessage(dynamicLinkEventArgs?.ReceivedDynamicLink.Url.OriginalString);//simple method to display info
    }
```

**Comment by paulinon** [comment]
Hi @Hedorda,

I'd like you to verify a few things:

1. Check the app's bundle ID against the `ibi` parameter of the dynamic link and confirm that they match.
2. If you have the optional `ius` parameter added to the Dynamic Link, the custom scheme URL with matching value must be set in the app.
3. In the Capabilities tab of your app's Xcode project, verify if `Associated Domains` is enabled and add the following to the Associated Domains list: `applinks:{your_dynamic_links_domain}`. Check out this [guide](https://firebase.google.com/docs/dynamic-links/ios/receive#open-dynamic-links-in-your-app) for more details.
4. Verify if `https://{your_dynamic_links_domain}/apple-app-site-association` contains an entry for your app and if `{team-id}.{bundle-id}` values are correct for your app.

I look forward to hearing from you soon.

**Comment by Hedorda** [comment]
Hi @paulinon,

I already have written in steps list that i checked a lot of parameters. All the parameters that have been checked(multiple times): `ibi` parameter, `Associated Domains`, bundle id and team id in console and `apple-app-site-association`, debug page `?d=1` of link - all looks right and no errors messages anywhere.

**Comment by Hedorda** [comment]
Hi @paulinon,



> 1. Check the [OAuth 2.0 Client IDs](https://console.cloud.google.com/apis/credentials?project_) in Google Cloud Console, and make sure that your iOS app doesn't have a duplicate Bundle ID.

Checked - all right, no duplicates or missed Bundle ID

> 2. Make sure that your [debug view](https://firebase.google.com/docs/dynamic-links/debug) doesn’t have any warnings or errors as this could affect the link's behavior.

I have written it in last letter - no errors or wrong parameters there.

> 3. When you long tap the FDL and select "Open in Safari" option, it will disable the Universal Links in the device for your domain. FDL is using iOS Universal Links under the hood and FDL will not work correctly if it's disabled. To re-enable the Universal Links, you'll need to long tap the FDL and select the "Open in App" option.

I know about it and made sure that everything is correct. We also encountered the problem on at least three different devices with three different users

> 4. Enabling the app preview page on custom Dynamic Link is not required. However, it's recommended that you enable the app preview page to guarantee unique matches from Dynamic Links on iOS. The app preview page also more reliably sends users to the most appropriate destination (such as your app) by minimizing unnecessary system dialog and enabling users to navigate out of in-app browsers. You could check our docs [here](https://firebase.google.com/docs/dynamic-links/link-previews#app_preview_pages) for more details regarding iOS app preview pages.

Its not enbled for my project.

Can the problem has been caused with this[bug?](https://github.com/firebase/firebase-ios-sdk/issues/6978)
I've checked CocoaPods, but there is a right version of pods(9.0.0)

**Comment by kvzhkv** [comment]
Hello, I guess we have the same issue with custom domain FDL. We made some research & had conversation with firebase support. Here is what we came up to:
There is no problem with client side settings, the issue caused by incorrect behavior of firebase servers.
When we use FDL with domain provided by Firebase (aka `blabla.page.link`) everything works as expected. But switching to custom domain links with exactly the same settings makes it impossible to detect what dynamic link was the source of the app installation.
(I should notice that app preview page is switched off in FDL settings, which is preffered as more straightforward user experience)

I'll try to explain FDL workflow with iOS devices as I understand it (target app is not installed on device):
1. User clicks on the link
2. Browser loads some blank html page with a bunch of JS code, which detects users platform, detects that target app is not installed & tries to **send some device metadata (the key part) to firebase servers (lang, iOS version, screen resolution etc.)**
3. As target app is not installed it opens AppStore
4. User installs application & opens it
5. Firebase SDK makes request to [firebase google api](https://developers.google.com/resources/api-libraries/documentation/firebasedynamiclinks/v1/java/latest/com/google/api/services/firebasedynamiclinks/v1/FirebaseDynamicLinks.V1.InstallAttribution.html) with same device metadata, firebase server makes fingerprint match & receives dynamic link that was initially clicked by user.

The main problem (the key part above) that sending metadata from browser is not working. Server responds with 405 errors. But when we use links with firebase provided domains server responds with 200 status codes.
Firebase support recognised it as wrong behavior.

You could try it out & tell me if I'm wrong.

**Comment by Hedorda** [comment]
> Thanks for the additional information, folks. In order to analyze what's causing the issue, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project that shows this behavior? You may use the [quickstart](https://github.com/firebase/quickstart-unity/tree/master/dynamic_links/testapp) as a baseline for troubleshooting. Make sure that no personally identifiable information is present in your implementation.

@paulinon, how we can do this? This issue applies exclusively to the behavior when there is an app in the App Store, so to reproduce the issue with quickstart app or MWE we should upload it to App Store, but strict moderation will not allow the application to pass.

**Comment by paulinon** [comment]
Hi @Hedorda,

Just to give an update, I haven't replicated your issue yet due to the App Store requirement, but I also observed the dynamic link being received by the app. That being said, it's possible that the cause of your issue is either something in the backend or in your configuration. 

I recommend that you redirect the issue to [Firebase Support](https://firebase.google.com/support) so that one of our agents can get in touch with you. You may include the information you provided in this thread along with other private information related to your configuration such as the output from our [self-diagnostic tool](https://firebase.google.com/docs/dynamic-links/debug#ios_self-diagnostic_tool) and your `apple-app-site-association` (AASA) file.
