### ISSUE TITLE
Firebase Database on Consoles ??

### ISSUE THREAD

**Issue by davoodkharmanzar** [firebase/firebase-unity-sdk#374]
hi,

is it possible to use Firebase Database on consoles?
like as XBOX one, PS4, Nintendo Switch and the great Google Stadia :]

thanks.

**Comment by argzdev** [comment]
Just bumping this thread, thank you for the feature request. However, Google Stadia has officially been shut down since January 18, 2023. As for xBox one, PS4, Nintendo Switch, you'll need to create a feature request in their specific support channels. That said, I'll go ahead and close this thread.
