### ISSUE TITLE
Can we specify the location of "google-services-desktop.json" to the Firebase Unity SDK?

### ISSUE THREAD

**Issue by jeunessacheng** [firebase/firebase-unity-sdk#428]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2022.1.3f1
  * Firebase Unity SDK version: 9.3.0
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Auth
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: Deskotop
  * Scripting Runtime: N/A
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: Pre-built

### [REQUIRED] Please describe the question here:
I am looking to include Firebase Authentication as part of custom Unity Editor functionality in a Unity package.  However, it seems there is a requirement that the `google-services-desktop.json` file be in `Assets/StreamingAssets` in the main project folder.  Is it possible to change the reference location for this json so the Firebase SDK is able to look for it inside the package instead of StreamingAssets?  The contents of the Firebase Auth SDK will also be included in the package as a dependency.

**Comment by paulinon** [comment]
Hi @jeunessacheng,

The `google-services-desktop.json` file is automatically generated once either the `GoogleService-Info.plist` or `google-services.json` file is detected in your project, and that file is also generated once it senses that either the file 
 or the `StreamingAssets` folder is missing. To answer your question, your use case isn't currently feasible.

Additionally, since the Auth SDK has its own package, it's recommended that you include it separately as the SDK is regularly being updated to fix any known issues or add useful features.

I'll be closing this for now. Feel free to reopen this if you have additional questions.
