### ISSUE TITLE
Generation of the Firebase Android resource file google-services.xml from Assets/Firebase/google-services.json failed.

### ISSUE THREAD

**Issue by isoueu** [firebase/firebase-unity-sdk#45]
Generation of the Firebase Android resource file google-services.xml from Assets/Firebase/google-services.json failed.

I couldn't reply in proper issue so i create a new.

I have been executed generate_xml_from_google_services_json.exe -i "Assets/Firebase/google-services.json" -l in a adminstrator cmdline and get the follow error: missing api-ms-win-core-path-l1-1-0.dll

Already got arround 10000 virus and suckingwares trying to fix this error, please compile generate_xml_from_google_services_json.exe independent unique file if you want someone use this SDK,

Thanks

**Comment by isoueu** [comment]
Also now my Unity Editor don't open anymore, even with a new project, should I Format the PC ? thankyou for your great pack

**Comment by chkuang-g** [comment]
Hi @isoueu 

Sorry for the late reply. 

May I get some more information about your situation?

- Which Unity SDK version are you using?
- What's the Windows version you are using?
- Does [this post](https://answers.microsoft.com/en-us/windows/forum/all/api-ms-win-core-path-l1-1-1ddl-is-missing/b7afd65f-b4f6-4868-8433-587a543532e5) works to fix the missing `api-ms-win-core-path-l1-1-0.dll`?
- @chriswalz since you upvoted this, could you describe your situation as well?

Thank you,
Shawn
