### ISSUE TITLE
[Question] Sanity check: firestore + unit tests + Unity + security rules, have I understood it correctly?

### ISSUE THREAD

**Issue by pogestudio** [firebase/firebase-unity-sdk#543]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.24f1
  * Firebase Unity SDK version: 10.1.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: ??
  * Other Firebase Components in use: ??
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: pre-built

### [REQUIRED] Please describe the question here:
I have been developing happily, a cloud firestore + cloud function + firestore auth chat app in unity.
Now I added security rules, and all unit tests fail. In my security rules I am requiring that the user is authenticated, and in my unit tests (for ex. create chat group function, which is a multi step process) I am mocking users. So it makes sense.

It feels like I have written my logic wrong since the way I am writing it kills all my unit tests xD So, if **anyone could be so kind to confirm:**

**1)** It is appreciated for security rules to have a check if the user is authenticated for a read/write.
**2)** You cannot unit test actions that require that a user should be authenticated in the client side (with unity sdk) since FB Auth in emulator is not supported
**3)** If 1+2) is correct, then recommended action is to refactor so that
**3.1)** functionality related to data is done with cloud functions
**3.2)** the client side code becomes simplified (complexity shifts to backend), only doing reads/writes/updates which is unit tested by team firebase.
**3.3)** unit tests which demands authentication (stuff dealing with db) are moved to an environment where user can be mocked (like in @firebase/rules-unit-testing).

Another way could be to not check authentication but that does not feel great.
I assume it will take me a little while to refactor so appreciate any input on whether I am in the right direction. Thanks for your time.

**Comment by paulinon** [comment]
Hi @pogestudio,

Thank you for filing this. Here's what I have to say regarding your questions:

1. It is recommended that you make use of security rules that restricts read and write access to your users, and authenticating users is the way to go. You may check out our [documentation](https://firebase.google.com/docs/firestore/security/insecure-rules) for more ways to fix insecure rules.

2. As of writing, the emulator for Unity is not yet implemented, but our team is working on it. You may refer to this [ticket](https://github.com/firebase/quickstart-unity/issues/1229) for updates.

3. My understanding here is that you plan to refactor your code for your unit tests. I'm not entirely familiar with your use case, but have you used our Rules Playground? It's a feature that lets you simulate Firebase operation with your security rules, and it could be found in the [Rules tab](https://console.firebase.google.com/project/_/firestore/_/rules) of your project. You may be able to modify your unit testing around this. Otherwise, or if you're out of other ways to perform unit testing, then the steps you listed seem actionable. You may raise this to [Stack Overflow](https://stackoverflow.com/questions/tagged/firebase) so that you can gather more input from other developers.

That said, I'll be closing this for now. Feel free to ask this to be reopened if you think this is a mistake. Let me know if an issue arises.
