### ISSUE TITLE
[Question] Get document from firestore collection using converto not working

### ISSUE THREAD

**Issue by licexicel** [firebase/firebase-unity-sdk#584]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.14
  * Firebase Unity SDK version: 10.1
  * Problematic Firebase Component: Firestore
  * Other Firebase Components in use: Auth 
  * Additional SDKs you are using:  AdMob
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: iOS, Android
  * Scripting Runtime:  IL2CPP

### [REQUIRED] Please describe the question here:
`Query MarketPostQuery = GameDataManager.FirebasFirestoreInstance.Collection("MarketPost");`
`QuerySnapshot snapshot = await MarketPostQuery.GetSnapshotAsync();`
`foreach (DocumentSnapshot Doc in snapshot)`
`MarketItems NewItems = Doc.ConvertTo<MarketItems>();`  (not working)
`NewItems = Doc.GetValue<MarketItems>("MarketItems");`  (works)
`string Name = Doc.GetValue<string>("MarketItems.Name");` (also works)
writing in two types above should be same if I comprehensed right from document,
but only the second tpye works.
The first type pop up with "No writable property for Firestore field MarketItems in type MarketItems"
The class MarketItems is make up of eight string variable.

![1](https://user-images.githubusercontent.com/37893175/209554399-2cd76542-b01a-4607-82e5-1d6433a11e4f.png)
![2](https://user-images.githubusercontent.com/37893175/209554408-b261dcdb-3d7f-4176-bdb0-c7c68f29125b.png)
![3](https://user-images.githubusercontent.com/37893175/209554416-6eace0d2-5526-45d4-b563-bd403ee751de.png)

**Comment by paulinon** [comment]
Hi @licexicel,

Thanks for reporting this. I see that using the `ConvertTo<T>` method doesn't work for your implementation. This is usually applied to a task result which is seen when using a continuation such as `ContinueWithOnMainThread` in your code. It should look something like this:

```
Query MarketPostQuery = GameDataManager.FirebaseFirestoreInstance.Collection("MarketPost");
MarketPostQuery.GetSnapshotAsync().ContinueWithOnMainThread(task => {
   QuerySnapshot snapshot = task.Result;
    foreach (DocumentSnapshot Doc in snapshot.Documents){
        MarketItems NewItems = Doc.ConvertTo<MarketItems>();
    }
);
```

I'll be closing this for now. In case an issue arises with this solution, let me know by providing any relevant information (such as a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)) so that this ticket can be reopened.

**Comment by licexicel** [comment]
It's weird that I did use convertTo on another script,
but that script didn't wrap the field into a class, inside document with field directly.
And I retried some other forms to get the data,
sure that with the previous code in picture above with getValue will work.(both DocumentRef or Query)
Also check there's no rules issue, all file read is true.
Append  a picture of the MarketItems class
![6](https://user-images.githubusercontent.com/37893175/209566118-19b8a976-4805-4ce2-87a1-7dc0cb2a85fd.png)

**Comment by paulinon** [comment]
Hi @licexicel,

Just to be sure that you have the latest fixes and updates, could you confirm if the issue persists using the latest SDK version (10.3.0 as of writing)? If so, please provide a minimal, reproducible example that I could run so that we can identify what's causing this behavior. I've been unsuccessful in encountering the warning message so far.
