### ISSUE TITLE
[Question] android.permission.ACCESS_NETWORK_STATE should be added?

### ISSUE THREAD

**Issue by calinpavel787** [firebase/firebase-unity-sdk#592]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.11f1
  * Firebase Unity SDK version: 10.3.0
  * Source you installed the SDK: .unitypackage 
  * Problematic Firebase Component: Analytics, Crashlytics
  * Other Firebase Components in use: described above
  * Additional SDKs you are using: Furioos, PureWeb, Zinnia, Zenject
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: Android 
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: n/a

### [REQUIRED] Please describe the question here:

For all the Analytics events in my project, I'm receiving a logcat that says: "Permission not granted: android.permission.ACCESS_NETWORK_STATE". Should I add the permissions on my own or is this a bug?

**Comment by paulinon** [comment]
Hi @calinpavel787,

I've tested this on a sample project, and I'm not facing the logs you indicated. I have a few questions regarding this:
- In order to identify what's causing this behavior, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation? You may use our [quickstart](https://github.com/firebase/quickstart-unity/tree/master/analytics/testapp) as a baseline for troubleshooting. 
- Could you also verify if you're facing a similar behavior with just the Firebase SDK in your project? 
- Lastly, could you also confirm if this log appears on more than one device? If so, please provide the device models and their respective Android versions.

**Comment by calinpavel787** [comment]
Hi @paulinon,

> * In order to identify what's causing this behavior, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation? You may use our [quickstart](https://github.com/firebase/quickstart-unity/tree/master/analytics/testapp) as a baseline for troubleshooting.

There's nothing in addition to what you guys provided in the documentation. I must say that I'm testing Analytics on iOS as well, and everything works fine there. 

> * Could you also verify if you're facing a similar behavior with just the Firebase SDK in your project?

This will actually take me 1/1.5 days because the project is huge. But since I'm out of options, I think I might go on this path.

What I'm trying right now in parallel is to update a Firebase version in another project that I have on my computer to check if is a problem of my computer.

> * Lastly, could you also confirm if this log appears on more than one device? If so, please provide the device models and their respective Android versions.

Samsung Galaxy A40 (Android 11)
Samsung Galaxy Tab S7 (Android 13)
Samsung Galaxy A50 (Android 11)


I want to add also that adding ```android.permission.ACCESS_NETWORK_STATE``` within the AndroidManifest of the app (Assets/Plugins/Android) doesn't solve the issue.

**Comment by calinpavel787** [comment]
Hello guys, I found out that I had in a high-priority AndroidManifest a `tools:node="remove"` tag for the ACCESS_NETWORK_STATE permission and that was removing the permission from the default manifest of the APK.

So removing that tag was solving the issue.
