### ISSUE TITLE
[Bug] FirebaseUser Reload method fails to update IsEmailVerified flag on Android.

### ISSUE THREAD

**Issue by marcusx2** [firebase/firebase-unity-sdk#619]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.8f1
  * Firebase Unity SDK version: 10.3.0
  * Source you installed the SDK: unitypackage  (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Auth (Auth, Database, etc.)
  * Other Firebase Components in use: N/A (Auth, Database, etc.)
  * Additional SDKs you are using: N/A (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Windows (Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)
  * Scripting Runtime: Mono for testing purposes, IL2CPP for release (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: Pre-built SDK

### [REQUIRED] Please describe the issue here:

The Reload method from a FirebaseUser does not update its IsEmailVerified flag. It works in the editor, but on Android calling Reload even after verifying the email the flag remains false. I searched this on Google and apparently it's a problem that happens on various Firebase environments, not just the Unity SDK.

The current workaround is to simply sign in again, but it's not ideal. It would be nice if the Reload method worked on Android as well to update the isEmailVerified flag.

**Comment by paulinon** [comment]
Hi @marcusx2,

Thank you for bringing this to our attention. Could you provide a sample code (preferrably a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)) along with the complete steps to reproduce the issue so that we could isolate what's causing this behavior?

**Comment by marcusx2** [comment]
So there is really no secret to this. I don't have the time to create an example, but all you have to do is create the email (can be manually), then in the code use `SignInWithEmailAndPasswordAsync` to sign in, `SendEmailVerificationAsync` to send the verification email, and a button to proceed, where on click you reload the user and check the `IsEmailVerified` flag. You can use [this website](https://temp-mail.org/en/) for testing purposes.

**Comment by paulinon** [comment]
Thanks for the additional information, @marcusx2. I've tried these steps, but the `isEmailVerified` flag is true in both the editor and the device. Could you try if updating to the [latest SDK version](https://firebase.google.com/support/release-notes/unity#version_1040_-_january_26_2023) makes a difference? Also, is the `isEmailVerified` flag set to false across other Android devices? If so, could you provide a list of these devices indicating their OS version and other relevant specifications?

It would be helpful if you provide the sample code in your implementation so that we can identify what's causing this behavior. For additional context, I used the [quickstart](https://github.com/firebase/quickstart-unity/tree/master/auth/testapp) with the addition of this function, and I was unable to replicate the behavior you described:

```
void FirebaseUserReload()
    {
      auth.SignInWithEmailAndPasswordAsync(email, password).ContinueWith(task => {
        if (task.IsCanceled) {
          Debug.LogError("SignInWithEmailAndPasswordAsync was canceled.");
          return;
        }
        if (task.IsFaulted) {
          Debug.LogError("SignInWithEmailAndPasswordAsync encountered an error: " + task.Exception);
          return;
        }
        Firebase.Auth.FirebaseUser newUser = task.Result;
        Debug.LogFormat("User signed in successfully: {0} ({1})", newUser.DisplayName, newUser.UserId);
        if (newUser != null) {
          newUser.SendEmailVerificationAsync().ContinueWith(task => {
          if (task.IsCanceled) {
            Debug.LogError("SendEmailVerificationAsync was canceled.");
            return;
          }
          if (task.IsFaulted) {
            Debug.LogError("SendEmailVerificationAsync encountered an error: " + task.Exception);
            return;
          }
          Debug.Log("Email sent successfully.");
          });
        }
      });
      DisableUI();
      EnableUI();
    }
```

**Comment by marcusx2** [comment]
If it's working for you, then I don't know. That code is pretty much what's done here. I am already using the latest sdk. Maybe it's an issue with my specific Android device then, a Samsung S8. Like I said, it works in the editor, just not on my Android.

**Comment by marcusx2** [comment]
No wait, when I say reload, is not the FirebaseUserReload method you showed me. You call that first. Then you have a button to proceed.  After tapping on that button, you call https://firebase.google.com/docs/reference/unity/class/firebase/auth/firebase-user#reloadasync and after the reload you check if the email is verified.

**Comment by paulinon** [comment]
Hi @marcusx2,

The quickstart contains the `ReloadAsync` function as seen [here](https://github.com/firebase/firebase-unity-sdk/issues/619#issuecomment-1424428916). The `FirebaseUserReload` method I provided is used when signing in after providing both email and password so that an email for user verification can be sent. This would be the new function that would be triggered after clicking "Sign In With Email". 

I've provided a [sample project](https://github.com/paulinon/repro-sdk-619) based on the quickstart for you to use. Could you try it and see if the issue persists in your device?
