### ISSUE TITLE
[Bug] DllNotFoundException: FirebaseCppApp-10_2_0 assembly: type: member:(null)

### ISSUE THREAD

**Issue by Sonhokko** [firebase/firebase-unity-sdk#625]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.3f1/2021.3.4f1
  * Firebase Unity SDK version:  10.2.0
  * Source you installed the SDK: firestore.auth(.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: _____ (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using:  (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Windows (Mac, Windows, or Linux)
  * Platform you are targeting: IOS/Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP_ (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _____

### [REQUIRED] Please describe the issue here:

After reinstalling Windows, after installing my project, when running in the unity playmode, I get this error from every service that touches the firebase in the slightest.

DllNotFoundException: FirebaseCppApp-10_0_2 assembly:<unknown assembly> type:<unknown type> member:(null)

the strangest thing is that I can build the project in apk or aab without any problems

Force resolve, deleting Library folder, reimporting SDK doesn't help

#### Steps to reproduce:

Reinstall windows, open unity project, launch playmode
#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulinon** [comment]
Hi @Sonhokko,

Thanks for this report. I noticed that the Unity SDK version you provided is 10.2.0 while the version in your exception message is 10.0.2 which doesn't exist. Is this perhaps a typo or maybe a version mismatch in your implementation? I'd like you to try if updating your SDK to its latest version ([10.4.0](https://firebase.google.com/support/release-notes/unity#version_1040_-_january_26_2023) as of writing) resolves the issue. Could you also try if updating your Unity editor (2021.3.18f1 is the latest LTS version as of writing) makes any difference?

**Comment by Sonhokko** [comment]
> 

Hi. 
Now i have error 
DllNotFoundException: FirebaseCppApp-10_2_0 assembly:<unknown assembly> type:<unknown type> member:(null)
Firebase.AppUtilPINVOKE+SWIGExceptionHelper..cctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/app/swig/Firebase.App_fixed.cs:4072)

I reimported firebase, this no help me. Why i have error for MAC if i use Windows? I not have path /Users/runner/work/firebase-unity-sdk on my PC

**Comment by paulinon** [comment]
Hi @Sonhokko,

This exception can be caused various issues. In your Unity editor, if you look under Firebase/Plugins/x86_64, is there a FirebaseCppApp-x_x_x.bundle file? Is it correctly being included for the editor, and using 'Any CPU'? Did an SDK update and/or Unity editor update make any difference?

**Comment by quangvinh2080** [comment]
I have this issue also,

Editor version: 2021.3.8f1
Firebase Unity SDK version: 10.4.0

```
DllNotFoundException: FirebaseCppApp-10_4_0 assembly:<unknown assembly> type:<unknown type> member:(null)
Firebase.AppUtilPINVOKE+SWIGExceptionHelper..cctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/app/swig/Firebase.App_fixed.cs:4072)
Rethrow as TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
Firebase.AppUtilPINVOKE..cctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/app/swig/Firebase.App_fixed.cs:4092)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.AppUtilPINVOKE' threw an exception.
Firebase.AppUtil.SetLogFunction (Firebase.LogUtil+LogMessageDelegate arg0) (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/app/swig/Firebase.App_fixed.cs:4802)
Firebase.LogUtil..ctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/app/src/LogUtil.cs:81)
Firebase.LogUtil..cctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/app/src/LogUtil.cs:37)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.LogUtil' threw an exception.
Firebase.FirebaseApp..cctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/app/swig/Firebase.App_fixed.cs:2014)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.FirebaseApp' threw an exception.
FirebaseSetup.Start () (at Assets/Scripts/FirebaseSetup.cs:15)
```

I have tried Force Resolve, restart Unity, but it still not works

**Comment by quangvinh2080** [comment]
I used version 10.1.0 and it worked normally, the bug appears from 10.2.0

**Comment by paulinon** [comment]
Thanks for the update, @quangvinh2080. When you mentioned that you reinstalled Windows, did you update the OS to a later version? Could you provide the OS version you've used Unity on? Could you also confirm if the device you're working on makes use of an updated C++ Redistributable? The reinstall may have caused library to fail due to not having a C++ Redistributable.

**Comment by quangvinh2080** [comment]
@paulinon I used Unity in Linux (Ubuntu 20.04). Could you test on it ? I haven't tried in Windows. But like you said, I think Windows will be fine

**Comment by leadhouse-patrick** [comment]
I do have the same issue.
It did start 3 weeks ago with Firebase 8.0. 
Updating the SDK to 10.4.0 did not fix the issue, then, suddenly, everything went well without any modification on the build for almost 2 weeks.
This morning, I noticed the issue was back again (again, without any modification). Updating it to 10.5.0 did not correct the issue.  In an early comment, it is written that it was working in 10.0.0, but did not work for me. 

**Here is the info about my build:**
Unity version: **2021.3.17f1**
Tested with Firebase sdk versions:  10.0.0, 10.1.1, 10.4.0, 10.5.0
Scripting backend: mono
Api Compatibility level: .NET Standard 2.1
Dedicated Server - Linux    --> current Linux OS:   Ubuntu 20.04.3 LTS
(Build from Windows 10 computer)


**When executing:**
`
DllNotFoundException: FirebaseCppApp-10_1_1 assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) Firebase.AppUtilPINVOKE+SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_AppUtil(Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate)
  at Firebase.AppUtilPINVOKE+SWIGExceptionHelper..cctor () [0x000ef] in <4110b571368c4eb78911aa7da9cb4f25>:0
Rethrow as TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
  at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_generic_class_init(intptr)
  at Firebase.AppUtilPINVOKE..cctor () [0x00000] in <4110b571368c4eb78911aa7da9cb4f25>:0
Rethrow as TypeInitializationException: The type initializer for 'Firebase.AppUtilPINVOKE' threw an exception.
  at Firebase.AppUtil.SetLogFunction (Firebase.LogUtil+LogMessageDelegate arg0) [0x00001] in <4110b571368c4eb78911aa7da9cb4f25>:0
  at Firebase.LogUtil..ctor () [0x0000f] in <4110b571368c4eb78911aa7da9cb4f25>:0
  at Firebase.LogUtil..cctor () [0x00011] in <4110b571368c4eb78911aa7da9cb4f25>:0
Rethrow as TypeInitializationException: The type initializer for 'Firebase.LogUtil' threw an exception.
  at Firebase.FirebaseApp..cctor () [0x0004b] in <4110b571368c4eb78911aa7da9cb4f25>:0
Rethrow as TypeInitializationException: The type initializer for 'Firebase.FirebaseApp' threw an exception.
  at BackendManager.Initialize () [0x00011] in <7b9b4ca3a33547d6bd9a82644e12bab7>:0
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in <05089c1b6989455fb1452c627044bac4>:0
  at UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () [0x00002] in <3dde041251174133b8f03e5cc95ec0fe>:0
  at UnityEngine.UnitySynchronizationContext.Exec () [0x00056] in <3dde041251174133b8f03e5cc95ec0fe>:0
`

**Other observations:**
Executing a build on a Windows Server have a similar trouble
Executing on my Windows 10 computer as a dedicated server works.
