### ISSUE TITLE
[Bug] None of your spec sources contain a spec satisfying the dependency: `Firebase/Core (= 10.7.0)`

### ISSUE THREAD

**Issue by adityathoutam** [firebase/firebase-unity-sdk#668]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.21f
  * Firebase Unity SDK version: 10.7.0
  * Source you installed the SDK: .UnityPackage 
  * Problematic Firebase Component: Auth, Analytics etc 
  * Other Firebase Components in use: Auth, Analytics etc 
  * Additional SDKs you are using: Facebook, AdMob etc
  * Platform you are using the Unity editor on: Mac Intel
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP 
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: website

### [REQUIRED] Please describe the issue here:
Unable to build iOS workspace project with this version.
Build Log shows this error "None of your spec sources contain a spec satisfying the dependency: `Firebase/Core (= 10.7.0)`."
I'm using Intel mac, I did update everything, ran pod repo update as well. My XCode version is 14.3
I am able to solve this by removing "/" from Firebase/Core in the pods file.
Same issue with all firebase components I used from firebase, analytics crashlytics storage etc
Firebase/Core 10.7.0 doesn't work
FirebaseCore 10.7.0 works

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)
100%

**Comment by paulinon** [comment]
Hi @adityathoutam,

Thanks for reporting this issue. I tried reproducing this issue on my end, but I haven't been successful. I have a few questions about the behavior you're facing:

- Are you able to reproduce this using the [quickstart](https://github.com/firebase/quickstart-unity)? If not, please share the steps you performed in your project to replicate the issue so that we could identify what's causing this.
- Are you using more than one Firebase product in your implementation? If so, could you verify if all of them have the same version? It's possible that a version mismatch is causing this.
- Could you share the generated `Podfile` along with a screenshot of your iOS Resolver Settings (go to Assets > External Dependency Manager > iOS Resolver > Settings)?

**Comment by adityathoutam** [comment]
Hi @paulinon,

Yes, point 2 was the problem. I'm using multiple firebase products and missed updating one product.
Thank you for pointing it out, It would be great if someway firebase prompted this while building.
