### ISSUE TITLE
[Question] Network bandwith optimization

### ISSUE THREAD

**Issue by aixaCode** [firebase/firebase-unity-sdk#696]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2022.2.12f
  * Firebase Unity SDK version: 10.7
  * Source you installed the SDK: (.unitypackage)
  * Problematic Firebase Component: Functions, Database
  * Other Firebase Components in use: Storage, Auth
  * Additional SDKs you are using: Facebook
  * Platform you are using the Unity editor on: Mac, Windows
  * Platform you are targeting: iOS, Android
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity)

### [REQUIRED] Please describe the question here:
Hi,
We are trying to optimize network bandwith in our game.
I was searching for any information on how firebase SDK is handling this problem, but unfortunately there was no information available.
For example, using Unity WebRequest you have full control on the how the data is being packed, but using functions API this is not possible. Other example would be when adding listeners to database documents references, and receiving the snapshot
Do you use JSON to send data?
Is there any compression on the HTTP requests?

Thanks for you help.

**Comment by paulinon** [comment]
Hi @aixaCode,

Thank you for your question. Have you come across our documentation about [optimizing networking](https://firebase.google.com/docs/functions/networking)? You can do this by maintaining persistent connections in a function which could be done by either HTTP/S Requests or accessing Google APIs such as Cloud Pub/Sub. You can also test the load of your function so you can measure how many connections your function performs on average.

I'll be closing this for now. Let me know if you have any clarifications so that this ticket could be reopened.

**Comment by aixaCode** [comment]
@paulinon Thanks a lot, this is very helpful.

Just follow up questions:
- maintain persistent connections - can we also do it while using Unity SDK?
That's how I use my functions: `exports.test = FUNCTIONS.https.onCall((data, context) => {));`
- can you also see how much data are you sending and receiving?
