### ISSUE TITLE
Firebase Auth have some dependencies issues 

### ISSUE THREAD

**Issue by JankunChar** [firebase/firebase-unity-sdk#782]
Unity editor version: Unity  2021.3.27f1

Firebase Unity SDK version: Firebase_unity_sdk (11.2.0).

Problematic Firebase Component: Auth

Other Firebase Components in use: None(only auth)

Additional SDKs you are using:None(only auth)

Platform you are using the Unity editor on: Windows

Platform you are targeting: Android

Scripting Runtime:Mono

Pre-built SDK from the website : Firebase_unity_sdk (11.2.0).

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc) 1

What happened? How can we make the problem occur?

I am new to firebase. I have integrated firebase Auth version (11.2.0).

I am unity 2021.3.27f1. I have placed googleservices.json in Assets Folder. 

When i build the firebase and run in my mobile it shows  the error.

One or more Firebase dependencies are not present. Current dependency status: UnavailableOther

I have also used Asset/dependency manager/Android Resolve/Force Resolve/ It says resolved... 

When i click the Authenticate Phone Number. Nothing happens....

I have spent a  lot of time in googling the issue but havent find any useful solution. 

could any one can give solution. 

Thanks and Regards
James

**Comment by paulinon** [comment]
Hi @JankunChar,

Thanks for bringing this to our attention. Have you created a keystore and generated your SHA1 and SHA256 keys? If not, you can set your keystore from the Publishing Settings under your Player Settings and running
`keytool -list -v -keystore <path_to_keystore> -alias <key_name>`. Downloading a new `google-services.json` file is necessary after this step.

Otherwise, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation? We can use this as a baseline for our troubleshooting.

**Comment by JankunChar** [comment]
@paulinon  thanks for  you reply . I have entered sha1 and sha256 in  firebase console. and i have downloaded the latest googleservice.json file . Then only error happens. What i have to do for running the firebase sms successfully?

**Comment by JankunChar** [comment]
Hi Paulion 

I have attached testapp file in the below link .

[(https://www.dropbox.com/s/rtouakl3mwt80lh/testapp.rar?dl=1)]

This is my apk file

[https://www.dropbox.com/s/q9d98zlyeno0505/SmsError.apk?dl=1]

I have attached the keystore in asset files name(keystore.keystore). The password is fooya123.. 

Kindly do the needful.

**Comment by paulinon** [comment]
Thanks for the additional information, @JankunChar. Upon checking, it seems that you're using version 11.0.0 of the SDK as well as a more recent version of the quickstart. In order to solve the issue in the other ticket you mentioned, have you tried deleting the folders related to the SDK then importing a downgraded SDK version? Could you also provide debug logs that appear while you're running the app build?

**Comment by JankunChar** [comment]
@paulinon  Thanks for you reply. 

> have you tried deleting the folders related to the SDK then importing a downgraded SDK version? 

Actually i have opened the Fresh downloaded the Fresh Quick Start Master and then i have downloaded the 10.7.0 . I never installed Firebase 11 Version. 

>have you tried deleting the folders related to the SDK then importing a downgraded SDK version?

which Folder i have to delete.  What you are ask me to do. 

     1) Shall i  First Install firebase 11 and  then you ask me to install firebase 10.7.0 then i have to delete the old files. 

Are you ask me to do the above. 

I am using Fresh Recent  Quck Start master + 10.7.0 ... ( in the thread i have mentioned)..

in case if you upload the old quick start master it will help  for me . 

Kindly do the needful. My project is in live. So sms is receiving. I am in deep trouble. 

Kindly provide correct qucik start master + firebase version.

**Comment by paulinon** [comment]
HI @JankunChar,

Apologies for any confusion this may have caused. To clarify, the workaround for the issue described in #764 is to make use of the `VerifyPhoneNumber_DEPRECATED()` function in the latest quickstart project (change `VerifyPhoneNumber` to `VerifyPhoneNumber_DEPRECATED` in line 1027 of the `UIHandler.cs` file) with a downgraded version (10.7.0) of the SDK. If you're not facing the error message saying that `The type or namespace name 'AuthResult' does not exist` in your fresh quickstart project, then you may disregard what I said about deleting the folders related to the SDK then importing a downgraded SDK version.

I utilized the `testapp.rar` file you provied, but I'm facing the behavior described in #764 instead of nothing happening. Does any error message appear in your fresh project after tapping `Authenticate Phone Number`? If not, it would be helpful if you provide any logs that may appear as you test the app build so that we can determine what's causing this to happen. You may refer to this [page](https://docs.unity3d.com/Manual/android-debugging-on-an-android-device.html) for more information.

**Comment by JankunChar** [comment]
Hi Paulion  

I have downloaded the Fresh Unity Quick Start master and then i have installed firebase 10. 7.0.. It says  Nothing to Import, All Assets from this package are already in your project. I think there  10.7.0  package default inside the recent quick start master project .

![Forum8 7](https://github.com/firebase/firebase-unity-sdk/assets/138671726/3f440bc0-ab3b-46ad-9e48-cc96be2b6530)

The Error shows .. 

![Forum8 7 2](https://github.com/firebase/firebase-unity-sdk/assets/138671726/fe850ab5-0c32-4e44-b9aa-c1c76fb5a25d)

Once i  installed firebae 11 . the error goes.   But the error displays  Firebase Dependencies unavailable other 

I have changed the VerifyPhoneNumber_DEPRECATED()  to VerifyPhoneNumber. But nothing works. 

>deleting the folders related to the SDK then importing a downgraded SDK version

Which Folder i have to delete.Kindly mentioned it....

My project is in live. Sms is not receiving. So i am in deep trouble. So kindly provide the solutions with immediate effect.

**Comment by JankunChar** [comment]
Hello Firebase team 

Kindly reply. Did quick start master in github(recent version) + Firebase Version 11.0 or 11.2  are both sending sms or not. 

Did Live version  quick start master is working or not.  if works means which firebase version i have to use. 

Did the problem is universal or  myself only receiving this error message. 

Firebase Team Kindly  reply. 

**Edit : in case if you have change version . Kindly mention  in github that you must update to this version else  it wont works.**

**Comment by paulinon** [comment]
Hi @JankunChar,

The Firebase SDK isn't included in the quickstart project. Does the issue in your first screenshot persist when you import this [SDK](https://dl.google.com/firebase/sdk/unity/dotnet4/FirebaseAuth_10.7.0.unitypackage)? If so, please provide the steps you're doing to import the SDK. You may refer to the [readme.md](https://github.com/firebase/quickstart-unity/blob/master/auth/testapp/readme.md) file for detailed instructions on how to build the project.

Regarding your app build, I'd like you to provide the [debug logs](https://docs.unity3d.com/Manual/android-debugging-on-an-android-device.html) I previously asked for. Given that nothing is happening after tapping Authenticate Phone Number, it's possible that the backend could be causing this, and we'd need the debug logs in order to verify whether or not this is the case.

**Comment by JankunChar** [comment]
@paulinon  i will update soon.

**Comment by JankunChar** [comment]
@paulinon  Sorry For Delaying. I have downloaded fresh quick start unity master... and i have installed firebase 10.7 . It installed firebase auth. Previously  in my project there is a bug. So i have mentioned that  the firebase have default version  of firebase 10.7. i am wrong. i am so sorry for that message. 

I have changed the  Verifyphonenumber_deprecated to verifyphonenumber . But it shows the below error. 
![Error2](https://github.com/firebase/firebase-unity-sdk/assets/138671726/afc65f5d-5024-428b-9fbd-f2d033997987)

[Editor.txt](https://github.com/firebase/firebase-unity-sdk/files/12136152/Editor.txt)

i have attached the editor script. 

you have asked about debug. log. How can i give that details. Could  you share thought on that?????

**Comment by paulinon** [comment]
Hi @JankunChar,

[Version 11.3.0](https://firebase.google.com/support/release-notes/unity#version_1130_-_july_19_2023) of the SDK has been released. This means that you should be able to use the recent quickstart with the `VerifyPhoneNumber` function without issue. If the `One or more Firebase dependencies are not present` error message appears, could you try if Resolving or Force Resovling makes any difference?

Once you've successfully built your app, if tapping Authenticating Phone Number doesn't do anything as you initially reported, it would be helpful if you provide [debug logs](https://docs.unity3d.com/Manual/android-debugging-on-an-android-device.html) as you are running the app. From the link I provided, there are various methods to debug your app, but I frequently do this by connecting my device using a USB.

**Comment by JankunChar** [comment]
@paulinon   Thank for your reply.I have downloded version11.3.0 .. But the same error continues. In Build Settings i never choose Custom main maninfest to custom proguard file.  Is there any default i have to choose... Which one i have to choose . it  is empty... (because quick master is empty)
[Final.txt](https://github.com/firebase/firebase-unity-sdk/files/12160714/Final.txt)

![ForumUpload](https://github.com/firebase/firebase-unity-sdk/assets/138671726/e1437705-8864-4e91-b84e-da5fd43c448e)

 I have attached the debug. log (adb log file)...

So kindly do the needful..


 Kindly look up on it.

**Comment by paulinon** [comment]
Thanks for the update, @JankunChar. Just to clarify, I have a few questions related to your findings:

- When you mentioned "the same error continues," are you referring to `One or more Firebase dependencies are not present. Current dependency status: UnavailableOther`? If so, are you seeing this in your app build?
- I checked the debug logs you provided, Firebase initialization was unsuccessful with an error message saying `Failed to read Firebase options from the app's resources. Either make sure google-services.json is included in your build or specify options explicitly.` By chance, does the path to your Unity project contain any special character? 
- Does your implementation have a Assets/Plugins/Android/Firebase.androidlib folder that contains AndroidManifest.xml, project.properties and res/values/google-services.xml?

Additionally, enabling custom build files isn't necessary unless Android resolution fails in the editor.

**Comment by JankunChar** [comment]
Thanks Paulinon for you reply. .  I am refering to  One or more Firebase dependencies are not present. Current dependency status: UnavailableOther..

In My Android Project there is no folder  Assets/Plugins/Android/Firebase.androidlib folder that contains AndroidManifest.xml,

I have searched and found  the forum. The same error  continues in my project. 

[](https://github.com/firebase/firebase-unity-sdk/issues/761)

The Above forum applies to my Error. So  Kindly  notifies it and  rectifies the problem . 

Kindly reply when the problem will solved...

**Comment by paulinon** [comment]
Hi @JankunChar,

The issue that you referenced is a bug caused by non-ASCII characters in the path to your Unity project. That said, do you have any non-ASCII characters in your path?

If not, do you have an Assets/Plugins/Android/Firebase folder in your implementation? Starting Unity 2020, this has to be renamed to Assets/Plugins/Android/Firebase.androidlib, and it should contain AndroidManifest.xml, project.properties and res/values/google-services.xml.

**Comment by JankunChar** [comment]
@paulinon  thanks for you reply.. 

My Unity path lies in  G:\Fooya25-07-23\auth\testapp... This is the path . what do you mean by 

>non-ASCII characters in the path to your Unity project. 

I cant understand ur question... I have mentioned my path in first line. 

>do you have an Assets/Plugins/Android/Firebase folder in your implementation?

defaulty i dont have the above folder. When i try to convert into android build to ios build. the above folder has been created.. 

When i once again convert ios to android build.  When i run in android build  .

. Firebase dependecies unavailable other error has shown in my mobile.

**Comment by paulinon** [comment]
Hi @JankunChar,

Based on the path name you shared, it doesn't seem to contain any [non-ASCII characters](https://terpconnect.umd.edu/~zben/Web/CharSet/htmlchars.html). This means we can rule out the bug you previously mentioned as the cause of your issue.

One of the solutions in this [Stack Overflow thread](https://stackoverflow.com/questions/59043445/unity-in-android-failed-to-read-firebase-options-from-the-apps-resources) suggests that renaming Assets/Plugins/Android/Firebase to Assets/Plugins/Android/Firebase.androidlib resolves the issue. Could you try this out and see if it makes any difference in your implementation?

**Comment by CLOUDFIRE91** [comment]
@paulinon  i will update soon.

**Comment by CLOUDFIRE91** [comment]
Waiting for your update...

**Comment by paulinon** [comment]
Hi @CLOUDFIRE91, 

Does the error appear in the Unity editor or in your app build? If it's in your app build, could you share your latest debug logs as you're running the app?

Also, are you successful in using the solution you read from the forum you mentioned?

**Comment by CLOUDFIRE91** [comment]
@paulinon  i have tried to integrate  and replace the old firebase files in  my project. But it shows error. Did you have any solution for this problem. What is the current status. Did the problem has been solved. is there any update from your side...

**Comment by JankunChar** [comment]
Hi Firebase Team  Any updates... From your Side...

**Comment by paulinon** [comment]
Hi folks,

Apologies for the radio silence here. Could you try if the issue persists with the latest SDK version ([11.5.0](https://firebase.google.com/support/release-notes/unity#version_1150_-_september_21_2023))? Does enabling both `Custom Main Gradle Template` and `Custom Gradle Properties Template` from your Player Settings > Publishing Settings make any difference?

If neither of these steps worked, could you provide your latest debug logs of your build after adding this line of code in your `Start()` function:

`Firebase.FirebaseApp.LogLevel = Firebase.LogLevel.Debug;`

**Comment by JankunChar** [comment]
@paulinon  I am very highly disappointed .. So i  left the sms and activated Email in  my  app... Did you solve that problem. kindly answer me. I did not tested any new version. Previously i have posted one error. 

>IIn My Android Project there is no folder Assets/Plugins/Android/Firebase.androidlib folder that contains AndroidManifest.xml,

did you solved that error in new firebase version???  actually when i convert  quick start master in  ios build  .. asset/plugin/android/firebase.androidlib folder will created.... so some one mention that is the major problem. 

did you solved that problem. our of curiosity i am asking. I dont have mindset to work again and make my life trouble again. 

if you solve that problem.. kindly post me.. .. thanks for you radio silence.. ...........

**Comment by argzdev** [comment]
Hey folks, this issue looks more like a configuration issue rather than the SDK itself. Please refer to our documentation for a step by step guide how to properly setup Firebase Authentication. For a sanity check, I tested our Firebase Phone Authentication using Firebase Auth version `11.9.0` and Unity Editor version `2022.3.24f1` and it works properly. I was able to receive SMS OTP correctly.

One thing to take note is that Firebase Phone Authentication requires app verification in order to work:

For [Android](https://firebase.google.com/docs/auth/android/phone-auth#enable-app-verification):
> To use phone number authentication, Firebase must be able to verify that phone number sign-in requests are coming from your app. There are three ways Firebase Authentication accomplishes this:
> - Play Integrity API
> - reCAPTCHA

For [iOS](https://firebase.google.com/docs/auth/ios/phone-auth#enable-app-verification):
> To use phone number authentication, Firebase must be able to verify that phone number sign-in requests are coming from your app. There are two ways Firebase Authentication accomplishes this:
> - Silent APNs notifications
> - reCAPTCHA verification

Another tip for Android, If you're unable to setup Play Integrity API and would like to test receiving SMS OTP, you may use a device without Google Play Store to request an OTP via the reCAPTCHA process.

That said, I'll go ahead and close this thread.
