### ISSUE TITLE
[Bug] Name is too long. Type, maximum supported length, name: user property, 24, ALLOW_AD_PERSONALIZATION_SIGNALS

### ISSUE THREAD

**Issue by Nyankoo** [firebase/firebase-unity-sdk#802]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.27f
  * Firebase Unity SDK version: 11.0.0
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Analytics
  * Other Firebase Components in use: 
  * Additional SDKs you are using: AdMob
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _____

### [REQUIRED] Please describe the issue here:

When setting `ALLOW_AD_PERSONALIZATION_SIGNALS` with `FirebaseAnalytics.SetUserProperty`, the following error is thrown:
`Name is too long. Type, maximum supported length, name: user property, 24, ALLOW_AD_PERSONALIZATION_SIGNALS`

#### Steps to reproduce:
Add below code into a project.

#### Relevant Code:

```
FirebaseAnalytics.SetUserProperty("ALLOW_AD_PERSONALIZATION_SIGNALS", "true");
```

**Comment by paulinon** [comment]
Hi @Nyankoo,

Thanks for bringing this to our attention. The property name in the `SetUserProperty` function has a 24-character limit. In the case of your example, you may want to try this line of code which should perform the expected behavior:

`FirebaseAnalytics.UserPropertyAllowAdPersonalizationSignals = "true";`

Let me know how it goes.
