### ISSUE TITLE
[Question] What is FirebaseInstallations.unitypackage used for ?

### ISSUE THREAD

**Issue by Morgan-6Freedom** [firebase/firebase-unity-sdk#898]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.32
  * Firebase Unity SDK version: 11.6.0
  * Source you installed the SDK: unityPackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: None (Auth, Database, etc.)
  * Other Firebase Components in use: None (Auth, Database, etc.)
  * Additional SDKs you are using: None (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)
  * Platform you are targeting: iOS (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: from the website

### [REQUIRED] Please describe the question here:

What is the point of FirebaseInstallations.unitypackage ?

**Comment by a-maurice** [comment]
It is really only intended for power users, that want to have more control over Installation tokens.  Some products, like Cloud Messaging and Remote Config, use these tokens to uniquely identify the installed application, so that it can be used for A/B testing and such.  If for whatever reason you would like a way to delete those Installation tokens, or generate new ones, then you can use the FirebaseInstallations unityPackage for it.

For more information, you can check out: https://firebase.google.com/docs/projects/manage-installations?hl=en

**Comment by argzdev** [comment]
Since this question is already answered, I'll go ahead and close this.
