### ISSUE TITLE
[Bug] APK crashes after using Firebase in Unity Editor Version 2023.2.0f1 

### ISSUE THREAD

**Issue by Harsh-Khambhadiya** [firebase/firebase-unity-sdk#903]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2023.2.0f1
  * Firebase Unity SDK version: 11.6.0
  * Additional SDKs you are using: GooglePlayGamesPlugin-0.11.01.unitypackage
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) 

### [REQUIRED] 
Tried to create demo project to perform google play games sign in using Firebase authentication, for that I use the [GooglePlayGamesPlugin-0.11.01.unitypackage] and [FirebaseAuth] package after importing both just tried to build an apk with minimum target version of Android 9.0(API level 28) and maximum is Android 13.0 (API level 33) and then just build the apk after building i installed it on the device (S21 FE (Android 13)) then, at startup it shows little popup for playgames icon for validating after that app crashes.

// TODO(you): code here to reproduce the problem
```
using GooglePlayGames;
using GooglePlayGames.BasicApi;
using TMPro;
using UnityEngine;

public class Auth : MonoBehaviour
{
    public TextMeshProUGUI Detail;
    public string Token;

    void Awake()
    {
        PlayGamesPlatform.Activate();
    }

    void Start()
    {
        Debug.Log("Authenticate");
        PlayGamesPlatform.Instance.Authenticate(status =>
        {
            if (status == SignInStatus.Success)
            {
                Debug.Log("\nSuccess\nRequestServerSideAccess");
                PlayGamesPlatform.Instance.RequestServerSideAccess(true, code =>
                {
                    Debug.Log("Authorization code: " + code);
                    Token = code;
                });

            }
            else Debug.Log("Failure");
        });
    }
}

**Comment by paulinon** [comment]
Hi @Harsh-Khambhadiya,

In order to identify what's causing this to happen, could you provide the code you're using for Firebase Authentication along with the [debug logs](https://docs.unity3d.com/Manual/android-debugging-on-an-android-device.html) that are thrown when the app crashes? You may provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) (with all personally identifiable information scrubbed) as this could be used as a baseline for troubleshooting.

**Comment by paulinon** [comment]
Hi @Harsh-Khambhadiya,

In order to identify what's causing this to happen, could you provide the code you're using for Firebase Authentication along with the [debug logs](https://docs.unity3d.com/Manual/android-debugging-on-an-android-device.html) that are thrown when the app crashes? You may provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) (with all personally identifiable information scrubbed) as this could be used as a baseline for troubleshooting.
