### ISSUE TITLE
[Bug] AnalyticsFixPropertyRemover for Unity 2021 

### ISSUE THREAD

**Issue by Kilatif** [firebase/firebase-unity-sdk#994]
### Description

Faced with exactly issue that was described here:
https://github.com/firebase/firebase-unity-sdk/issues/945

But on Unity 2021 version with gradle 4.0.1
So, for some reason "removeAll" tools:node don't work for property element

Need to say, that removing this "removeAll" hack in my case can't be applied, because then "property" element issue appears in "jetfied-play-services-measurement-api-21.5.1" 

So, do you have any quick fixes for AnalyticsFixPropertyRemover or to avoid "property" element issue?

Issue with "removeAll":
![image](https://github.com/firebase/firebase-unity-sdk/assets/632354/3af9229c-4f6b-4926-b479-215463de0393)

Issue with "property" if disable "removeAll" hack:
![image](https://github.com/firebase/firebase-unity-sdk/assets/632354/38891705-5392-4a32-ad3c-418a9b45475a)

### Firebase Unity SDK Version

11.8.1

### Unity editor version

2021.3.33f1

### Installation Method

Unity Package Manager

### Problematic Firebase Component(s)

Messaging

### Targeted Platform(s)

Android

### Unity editor platform

Mac

### Scripting Runtime

IL2CPP

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity

### If using CocoaPods for Apple platforms, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

👀 Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by a-maurice** [comment]
Near the top of your AndroidManifest file, you should have something along the lines of:
`<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.unity3d.player" xmlns:tools="http://schemas.android.com/tools">`

That xmlns:tools section is the important part, as that needs to be defined in that section, instead of the property removeAll tag.  That should just be:
`<property tools:node="removeAll" />`
